### ISSUE TITLE
Modulisation

### ISSUE THREAD

**Issue by BomBardyGamer** [KryptonMC/Krypton#28]
### Description

Split Krypton in to more modules, to allow for two things:
1. Use of them outside of the scope of this project
2. Ease of reuse

Potential candidates for module separation:
- The authentication mechanism (`org.kryptonmc.krypton.auth`)
- The protocol (`org.kryptonmc.krypton.packet`)
- The event system (`org.kryptonmc.api.event` and `org.kryptonmc.krypton.event`)

**Comment by Forbidden-A** [comment]
I'd say this is a higher priority imo

**Comment by BomBardyGamer** [comment]
I'm going to close this PR, as this has been addressed, and the following is the result:
- The authentication mechanism will not be split
- The protocol will be split as part of #53 
- The event system will not be split (at the moment)
