### ISSUE TITLE
Adventure Pointers Support

### ISSUE THREAD

**Issue by 4drian3d** [KryptonMC/Krypton#82]
### Description

It seems that Krypton does not support Adventure Pointers, since their classes that implement the Audience class do not override the [pointers()](https://jd.adventure.kyori.net/api/4.11.0/net/kyori/adventure/pointer/Pointered.html#pointers()) method, for example: https://github.com/KryptonMC/Krypton/blob/master/server/src/main/kotlin/org/kryptonmc/krypton/console/KryptonConsole.kt and https://github.com/KryptonMC/Krypton/blob/master/server/src/main/kotlin/org/kryptonmc/krypton/user/KryptonUser.kt

### Steps to reproduce

For example when trying to use the KryptonConsole#pointers().supports(`any pointer`) method, it will return false since the default Pointers returned is a Pointers.empty() https://github.com/KyoriPowered/adventure/blob/main/4/api/src/main/java/net/kyori/adventure/pointer/Pointered.java#L91 which does not have any information

### Expected behaviour

That the pointers are implemented in the main classes that implement Audience

### Details

* Server version: Krypton 0.66.3
* Java version: 17

### Other information

An example of pointer implementation is how Paper and Velocity implement it https://github.com/PaperMC/Velocity/blob/1a3fba4250553702d9dcd05731d04347bfc24c9f/proxy/src/main/java/com/velocitypowered/proxy/console/VelocityConsole.java#L57

Pointers are important for multiplatform plugins, since they allow to obtain common information (like the PermissionChecker) without the need of having a specific logic for each platform

**Comment by BomBardyGamer** [comment]
Fixed in 5e70bac3ecbc2d4d0a8144809371e0d0b91de503
